support topologySpreadConstraint in pod spec schema
hashicorp/terraform-provider-kubernetes pull request #1022
Opened 2020-09-29 20:21 UTC by DrFaust92

### Description

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/master/CHANGELOG.md):

```release-note
...
```

### References

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

2020-10-13 09:36 UTC, weeco commented
Hey @DrFaust92 ,
thanks for working on this. Is this still a Draft PR / work in progress or is it ready to be reviewed?

2020-10-13 09:39 UTC, DrFaust92 commented
It can be reviewed. Having issue with making this work properly. Feel free to review/test

2020-12-10 02:17 UTC, llamahunter commented
What's the status of this PR?  1.18 has added beta level support for pod topology spread, so this is kind of required now.

2021-02-04 03:11 UTC, maynardflies commented
@DrFaust92 I think maybe you need to set the status of this PR to be ready to review as it is still draft right now.  Hoping we can get this merged ASAP as with 1.19 this is now mainstream and we are itching to use it!

2021-02-13 03:43 UTC, llamahunter commented
Is this work abandoned?  It's kind of tragic that this is _still_ not supported.

2021-02-13 16:19 UTC, DrFaust92 commented
Rebsed, added some minor changes and retested!

2021-02-13 16:25 UTC, DrFaust92 commented
Missing some docs, on it

2021-02-16 02:55 UTC, jrhouston requested changes
Thanks for adding this @DrFaust – just a small fix to the validation for `max_skew`.

2021-02-16 02:55 UTC, jrhouston commented on kubernetes/schema_pod_spec.go
> +						ValidateFunc: validation.IntNotInSlice([]int{0}),
I think here you want [validation.IntAtLeast(1)](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/helper/validation#IntAtLeast) as the the int can't be a negative number.

The docs for this field are not super clear, but if you look at the code the `<= 0` condition is here: https://github.com/kubernetes/kubernetes/blob/e059af640627c7be36b00c1d10a4d511e283d9b4/pkg/scheduler/apis/config/validation/validation_pluginargs.go#L134

2021-02-16 02:55 UTC, jrhouston commented on website/docs/r/pod.html.markdown
> +* `max_skew` - (Optional) Describes the degree to which pods may be unevenly distributed.
Should say that this Defaults to `1`

2021-02-24 18:05 UTC, ichtiosapiens commented
@DrFaust92 great job with that feature. It would be nice to have it in the next release. Do you need a hand with review comments?

2021-02-24 22:21 UTC, DrFaust92 commented
@jrhouston, Thanks for the comments. ive addressed the changes :D

2021-02-25 18:26 UTC, jrhouston approved these changes

2021-02-25 18:26 UTC, merged

2021-03-04 23:51 UTC, llamahunter commented
is there a plan for a release soon so that we can make use of this feature?

2021-03-05 16:40 UTC, aareet commented
@llamahunter we cut a release at the end of our sprints, so one should be due next week