Add `ip_families` and `ip_family_policy` attributes to `kubernetes_service`
hashicorp/terraform-provider-kubernetes pull request #1662
Opened 2022-03-25 13:03 UTC by arybolovlev

### Description

This PR adds two more attributes to the resource and data source of `kubernetes_service`:
- `ip_families`
- `ip_family_policy`

### Acceptance tests
- [X] Have you added an acceptance test for the functionality being added?
- [X] Have you run the acceptance tests on this branch?

Output from acceptance testing:

Data source:
```
$ make testacc TESTARGS='-run ^TestAccKubernetesDataSourceService_basic'

=== RUN   TestAccKubernetesDataSourceService_basic
--- PASS: TestAccKubernetesDataSourceService_basic (3.67s)
PASS
ok  	github.com/hashicorp/terraform-provider-kubernetes/kubernetes	5.807s
```

Resource:
```
$ make testacc TESTARGS='-run ^TestAccKubernetesServiceV1_ipFamilies'

=== RUN   TestAccKubernetesServiceV1_ipFamilies
--- PASS: TestAccKubernetesServiceV1_ipFamilies (2.35s)
PASS
ok  	github.com/hashicorp/terraform-provider-kubernetes/kubernetes	2.879s
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md):

```release-note
Add `ip_families` and `ip_family_policy` attributes to `kubernetes_service`
```

### References

Resolves:
- https://github.com/hashicorp/terraform-provider-kubernetes/issues/1553

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

2022-03-29 13:45 UTC, arybolovlev commented on kubernetes/data_source_kubernetes_service_test.go
> +	ip_family_policy = "SingleStack"
These two values are default and I put them here to make the test looks more explicit.

2022-04-08 18:09 UTC, jrhouston requested changes
couple small things

2022-04-11 15:06 UTC, arybolovlev commented on kubernetes/data_source_kubernetes_service.go
> +	api "k8s.io/api/core/v1"
Done, thank you! I made it `corev1`.

2022-04-11 15:24 UTC, jrhouston approved these changes

2022-04-14 12:23 UTC, merged