Add Terraform Config for provisioning aks cluster
hashicorp/terraform-provider-kubernetes pull request #2030
Opened 2023-03-06 19:19 UTC by sheneska

### Description

This PR created a new terraform configuration for provisioning aks clusters.

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md):

```release-note
...
```

### References

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

2023-03-07 19:51 UTC, BBBmau requested changes
After doing the requested changes, i was able to provision the cluster successfully!

2023-03-07 19:51 UTC, BBBmau commented on kubernetes/test-infra/aks-new/main.tf
> +  default = "West Europe"
Attempted to run with `West Europe`, we currently have reached our quota for this region. Changing it to `West US` works just fine.

2023-03-07 19:51 UTC, BBBmau commented on kubernetes/test-infra/aks-new/main.tf
> +  features {}
when attempting to use `export ARM_SUBSCRIPTION_ID` it doesn't seem to apply the id correctly. Using the attribute `subscription_id` within the provider block solves this issue.

2023-03-07 20:13 UTC, BBBmau commented
be sure to add the copyright headers at the top of the file as well!

```
// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
```

2023-03-09 18:18 UTC, jrhouston approved these changes

2023-03-09 18:54 UTC, merged