feat: Support spec.persistentVolumeClaimRetentionPolicy in kubernetes_stateful_set
hashicorp/terraform-provider-kubernetes pull request #2333
Opened 2023-10-30 14:02 UTC by adinhodovic

### Description

Support spec.persistentVolumeClaimRetentionPolicy in kubernetes_stateful_set. Requires enabling the feature flag `StatefulSetAutoDeletePVC`. 

### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
TF_ACC=1 KUBE_CTX_CLUSTER=minikube KUBE_CONFIG_PATH=~/.kube/config KUBE_CTX_AUTH_INFO=minikube make testacc TESTARGS="-run=TestAccKubernetesStatefulSetV1"

TF_ACC=1 go test "/home/adin/oss/terraform-provider-kubernetes/kubernetes" -v -vet=off -run=TestAccKubernetesStatefulSetV1 -parallel 8 -timeout 3h
=== RUN   TestAccKubernetesStatefulSetV1_minimal
=== PAUSE TestAccKubernetesStatefulSetV1_minimal
=== RUN   TestAccKubernetesStatefulSetV1_basic
=== PAUSE TestAccKubernetesStatefulSetV1_basic
=== RUN   TestAccKubernetesStatefulSetV1_basic_idempotency
=== PAUSE TestAccKubernetesStatefulSetV1_basic_idempotency
=== RUN   TestAccKubernetesStatefulSetV1_Update
=== PAUSE TestAccKubernetesStatefulSetV1_Update
=== RUN   TestAccKubernetesStatefulSetV1_waitForRollout
=== PAUSE TestAccKubernetesStatefulSetV1_waitForRollout
=== CONT  TestAccKubernetesStatefulSetV1_minimal
=== CONT  TestAccKubernetesStatefulSetV1_Update
=== CONT  TestAccKubernetesStatefulSetV1_waitForRollout
=== CONT  TestAccKubernetesStatefulSetV1_basic_idempotency
=== CONT  TestAccKubernetesStatefulSetV1_basic
--- PASS: TestAccKubernetesStatefulSetV1_minimal (6.47s)
--- PASS: TestAccKubernetesStatefulSetV1_basic (24.96s)
--- PASS: TestAccKubernetesStatefulSetV1_basic_idempotency (28.57s)
--- PASS: TestAccKubernetesStatefulSetV1_waitForRollout (37.02s)
--- PASS: TestAccKubernetesStatefulSetV1_Update (90.94s)
PASS
ok      github.com/hashicorp/terraform-provider-kubernetes/kubernetes   90.969s
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md):

```release-note
feat: Support spec.persistentVolumeClaimRetentionPolicy in kubernetes_stateful_set
```

### References

Fixes #2282

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

2023-10-30 14:02 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-provider-kubernetes?pullRequest=2333)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-provider-kubernetes?pullRequest=2333)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-provider-kubernetes?pullRequest=2333).</sub>

2023-11-04 04:07 UTC, BBBmau requested changes
Looks to be good, just missing documentation of the attribute being added as well as a changelog-entry. It can be added in `website/docs/r/stateful_set_v1.html.markdown` and `website/docs/r/stateful_set.html.markdown`

2023-11-10 21:59 UTC, adinhodovic commented
> Looks to be good, just missing documentation of the attribute being added as well as a changelog-entry. It can be added in `website/docs/r/stateful_set_v1.html.markdown` and `website/docs/r/stateful_set.html.markdown`

Fixed!

2023-12-05 12:34 UTC, BBBmau commented
Thank you for your patience! Wanted to double check this since it had been while since this PR was open. All looks good, thank you for contributing!

2023-12-05 12:34 UTC, BBBmau approved these changes

2023-12-05 12:35 UTC, merged