TF Plugin Docs - namespace & RunTime Class
hashicorp/terraform-provider-kubernetes pull request #2470
Opened 2024-04-18 18:50 UTC by sheneska

### Description

This PR covers the following:

- migrates files from the legacy structure `(docs/r)` to the `tfplugindocs` supported `templates/` structure
- generates templated files for each resource & data source as well as example.tf files 
-  Edits template files to include `data fields` where possible 

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md):

```release-note
...
```

### References

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

2024-04-19 11:39 UTC, arybolovlev requested changes
I have left a few comments, could you please take a look? Most of them apply to all files in this PR, so I picked up only one and commented there.

One more thing that I have noticed -- doc-gen does not pick up default values. Do you know if there are plans to fix that? It might be crucial for some resources and timeouts.

All in all, great efforts, thank you!

2024-04-19 11:39 UTC, arybolovlev commented on templates/resources/secret_v1.md.tmpl
> +{{tffile "/Users/sheneskawilliams/dev/terraform-provider-kubernetes/examples/resources/secret_v1/example_1.tf"}}
Please replace absolute paths with relative ones.

2024-04-19 11:39 UTC, arybolovlev commented on templates/resources/secret_v1.md.tmpl
> +---
It looks like the content of each file duplicates. Starting from this line and till the end of the file is a duplicate.

2024-04-19 11:39 UTC, arybolovlev commented on templates/resources/namespace_v1.md.tmpl
> +page_title: "Kubernetes: kubernetes_namespace_v1"
Can we replace `kubernetes_namespace_v1` with `{{ .Name }}`?

2024-04-19 11:39 UTC, arybolovlev commented on templates/resources/namespace_v1.md.tmpl
> +  Kubernetes supports multiple virtual clusters backed by the same physical cluster. These virtual clusters are called namespaces.
Can we replace description here with `{{ .Description }}`?

2024-04-19 11:39 UTC, arybolovlev commented on kubernetes/resource_kubernetes_namespace_v1.go
> +			Delete: schema.DefaultTimeout(2 * time.Minute),
I think you used this one to validate doc-gen, could you please revert this change or share more details? :)

2024-04-19 11:39 UTC, arybolovlev commented on templates/resources/namespace_v1.md.tmpl
> +## Argument Reference
This part overlaps with what is rendered by `{{ .SchemaMarkdown }}`. Shell we remove it from here?

2024-04-24 10:30 UTC, SarahFrench reviewed
👋 Hi Sheneska, I saw your post on Slack and took a look at the problem.

It looks like you need to update these files to reflect the new locations of the markdown files:
- This line in [.github/workflows/markdown-link-check.yaml](https://github.com/hashicorp/terraform-provider-kubernetes/blob/4f75983bd1e39f1444337934336673ac26d11a31/.github/workflows/markdown-link-check.yaml#L11)
- Times that [the Makefile](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/GNUmakefile) references the old `./website` path. The Makefile is used in the [checkers-and-linters.yaml file](https://github.com/hashicorp/terraform-provider-kubernetes/blob/4f75983bd1e39f1444337934336673ac26d11a31/.github/workflows/checkers-and-linters.yml#L31-L40), which is linked to one of the checks that's failing.

2024-04-25 15:54 UTC, arybolovlev approved these changes

2024-04-25 15:56 UTC, merged